{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T09:56:03.041Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T09:56:03.044Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T09:56:17.318Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T09:56:17.319Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:06:54.952Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:06:54.952Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:06:56.313Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:06:56.314Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:06:56.758Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:06:56.758Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:06:58.459Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:06:58.459Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:06:58.901Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:06:58.903Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:06.061Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:06.062Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:08.432Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:08.432Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:09.227Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:09.228Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:33.516Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:33.516Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:37.441Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:37.442Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:38.593Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:38.594Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:07:59.755Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:07:59.756Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:08:03.673Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:08:03.674Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:08:23.474Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:08:23.474Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:09:27.383Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:09:27.383Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:09:56.426Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:09:56.427Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:10:53.683Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:10:53.684Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:11:27.889Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:11:27.889Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:17:22.367Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:17:22.368Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [localhost:27017] on first connect"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' }","timestamp":"2017-06-05T10:21:14.716Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n  name: 'MongoError',\n  message: 'failed to connect to server [localhost:27017] on first connect' } MongoError: failed to connect to server [localhost:27017] on first connect\n    at Pool.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/topologies/server.js:313:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/pool.js:260:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/mnt/data/Kawa-ParseServer/CloudCode/node_modules/mongodb-core/lib/connection/connection.js:162:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)","timestamp":"2017-06-05T10:21:14.716Z"}
